### ISSUE TITLE
Mainnet checklist

### ISSUE THREAD

**Issue by kcole16** [NearDeFi/burrow-cash#236]
- [x] Submit new code for audit (~2 weeks)
  - [x] xBRRR implementation
  - [x] Upgrade through DAO
    - [ ] Test upgrades
- [x] Testing BRRR farm on Beta
  - [x] Deploy BRRR to Beta
  - [x] Deploy frontend to Beta
  - [x] Medium post informing community
  - [x] Testnet frontend
    - [x] Show earned rewards on frontend
    - [x] Allow claiming rewards
  - [x] Show weekly rewards per asset
- [x] Identify actual number for token rewards
  - [x] First month total distribution
    - [x] For supplying
    - [ ] For borrowing
- [ ] Implementing boost and rewards handling on frontend
   - [ ] Show extra APY breakdown
   - [x] Add "Claim All" button for farms
   - [ ] Make it clear rewards need to be claimed and added as collateral for borrow mining
   - [ ] Show historical earned rewards over time
- [ ] Testing rewards on Beta (other than BRRR)
   - [ ] Give away small amount of USDC with APR
- [ ] Testing xBRRR staking and boosts on Beta
- [x] #240
- [x] Give Flux requirements for oracle
